# Converts the chosen icon set into a generated C++ table of SVG path data.
# Pure ASCII.
#
# The set stays the source of truth: change $set and the map below and rerun.
# Non-path elements (circle, rect, line) are reduced to path data here so the
# runtime only ever has to understand one thing.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$set  = Join-Path $PSScriptRoot 'icon-sets\lucide\package'
$dir  = Join-Path $set 'icons'
$ver  = (Get-Content (Join-Path $set 'package.json') -Raw | ConvertFrom-Json).version

# Icon enum order -> name in the set. This list IS the enum order; a mismatch is
# caught by a static_assert in the generated file.
$map = @(
  @{e='None';          n=''}
 ,@{e='Folder';        n='folder'}
 ,@{e='Doc';           n='file-text'}
 ,@{e='Pdf';           n='file-type'}
 ,@{e='Image';         n='file-image'}
 ,@{e='Video';         n='file-video'}
 ,@{e='Archive';       n='file-archive'}
 ,@{e='Audio';         n='file-music'}
 ,@{e='Code';          n='file-code'}
 ,@{e='App';           n='app-window'}
 ,@{e='Clock';         n='clock'}
 ,@{e='Desktop';       n='monitor'}
 ,@{e='Download';      n='download'}
 ,@{e='Star';          n='star'}
 ,@{e='Pc';            n='computer'}
 ,@{e='Drive';         n='hard-drive'}
 ,@{e='Cloud';         n='cloud'}
 ,@{e='Network';       n='network'}
 ,@{e='ChevronRight';  n='chevron-right'}
 ,@{e='ChevronLeft';   n='chevron-left'}
 ,@{e='ChevronDown';   n='chevron-down'}
 ,@{e='SidebarToggle'; n='panel-left'}
 ,@{e='Sort';          n='arrow-up-down'}
 ,@{e='Share';         n='share-2'}
 ,@{e='More';          n='ellipsis'}
 ,@{e='Search';        n='search'}
 ,@{e='Plus';          n='plus'}
 ,@{e='Gear';          n='settings'}
 ,@{e='ViewColumn';    n='columns-3'}
 ,@{e='ViewList';      n='list'}
 ,@{e='ViewIcon';      n='grid-2x2'}
)

function Num($v) {
  $d = [double]$v
  return $d.ToString('0.####', [Globalization.CultureInfo]::InvariantCulture)
}
function Attr($tag, $name, $default) {
  if ($tag -match ('(?:\s|^)' + $name + '\s*=\s*"([^"]*)"')) { return [double]$Matches[1] }
  if ($null -eq $default) { throw "attribute $name missing in: $tag" }
  return [double]$default
}

# Every element type Lucide actually uses, reduced to path data.
function ToPath($tag) {
  if ($tag -match '^<path') {
    if ($tag -match '\sd\s*=\s*"([^"]*)"') { return ($Matches[1] -replace '\s+', ' ').Trim() }
    throw "path without d: $tag"
  }
  if ($tag -match '^<circle') {
    $cx = Attr $tag 'cx' $null; $cy = Attr $tag 'cy' $null; $r = Attr $tag 'r' $null
    # two half-arcs: one arc cannot describe a full circle (start == end)
    return ('M {0} {1} A {2} {2} 0 1 0 {3} {1} A {2} {2} 0 1 0 {0} {1} Z' -f `
            (Num ($cx-$r)), (Num $cy), (Num $r), (Num ($cx+$r)))
  }
  if ($tag -match '^<line') {
    return ('M {0} {1} L {2} {3}' -f (Num (Attr $tag 'x1' $null)), (Num (Attr $tag 'y1' $null)),
                                     (Num (Attr $tag 'x2' $null)), (Num (Attr $tag 'y2' $null)))
  }
  if ($tag -match '^<rect') {
    $x = Attr $tag 'x' 0; $y = Attr $tag 'y' 0
    $w = Attr $tag 'width' $null; $h = Attr $tag 'height' $null
    $rx = Attr $tag 'rx' 0; $ry = Attr $tag 'ry' $rx
    if ($rx -le 0) {
      return ('M {0} {1} H {2} V {3} H {0} Z' -f (Num $x), (Num $y), (Num ($x+$w)), (Num ($y+$h)))
    }
    return ('M {0} {1} H {2} A {3} {4} 0 0 1 {5} {6} V {7} A {3} {4} 0 0 1 {2} {8} H {0} A {3} {4} 0 0 1 {9} {7} V {6} A {3} {4} 0 0 1 {0} {1} Z' -f `
      (Num ($x+$rx)), (Num $y), (Num ($x+$w-$rx)), (Num $rx), (Num $ry),
      (Num ($x+$w)), (Num ($y+$ry)), (Num ($y+$h-$ry)), (Num ($y+$h)), (Num $x))
  }
  throw "unhandled element: $tag"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// GENERATED by design/gen-icons.ps1 - do not edit by hand.')
[void]$sb.AppendLine("// Source: Lucide v$ver, ISC (some icons MIT, derived from Feather).")
[void]$sb.AppendLine('// The full licence text ships as THIRD-PARTY-NOTICES.txt and must stay with')
[void]$sb.AppendLine('// any binary built from this file.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace {')
[void]$sb.AppendLine('struct IconSrc { int count; const char* const* d; };')
[void]$sb.AppendLine('')

$total = 0
foreach ($m in $map) {
  if (-not $m.n) { continue }
  $f = Join-Path $dir ($m.n + '.svg')
  if (-not (Test-Path $f)) { throw "not in the set: $($m.n) (for Icon::$($m.e))" }
  $svg = Get-Content $f -Raw
  # body only; the <svg> wrapper carries presentation we override anyway
  if ($svg -notmatch '(?s)<svg[^>]*>(.*)</svg>') { throw "no svg body: $f" }
  $body = $Matches[1]
  $paths = @()
  foreach ($mm in [regex]::Matches($body, '(?s)<(path|circle|rect|line)\b[^>]*?/?>')) {
    $paths += (ToPath $mm.Value)
  }
  if ($paths.Count -eq 0) { throw "no drawable elements: $f" }
  $total += $paths.Count
  [void]$sb.AppendLine("const char* const kD_$($m.e)[] = {")
  foreach ($p in $paths) { [void]$sb.AppendLine('    "' + ($p -replace '"','\"') + '",') }
  [void]$sb.AppendLine('};')
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('const IconSrc kIconSrc[] = {')
foreach ($m in $map) {
  if ($m.n) { [void]$sb.AppendLine("    { static_cast<int>(sizeof(kD_$($m.e))/sizeof(*kD_$($m.e))), kD_$($m.e) },  // $($m.e) <- $($m.n)") }
  else      { [void]$sb.AppendLine('    { 0, nullptr },  // None') }
}
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('static_assert(sizeof(kIconSrc)/sizeof(*kIconSrc) == static_cast<size_t>(Icon::Count),')
[void]$sb.AppendLine('              "icon_data.inc is out of step with the Icon enum - rerun design/gen-icons.ps1");')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// The set is authored on a 24 unit grid.')
[void]$sb.AppendLine('constexpr float kIconGrid = 24.0f;')
[void]$sb.AppendLine('} // namespace')

$out = Join-Path $root 'src\icon_data.inc'
[IO.File]::WriteAllText($out, $sb.ToString(), (New-Object Text.UTF8Encoding $false))
Write-Host ("wrote {0}" -f $out)
Write-Host ("  {0} icons, {1} subpaths, from Lucide v{2}" -f ($map.Count-1), $total, $ver)

# The licence has to travel with the binary, so generate it from the real file.
$lic = Get-Content (Join-Path $set 'LICENSE') -Raw
$notice = @"
Third-party notices for Oriel
=============================

Oriel embeds icon outlines derived from the Lucide icon set (v$ver).
The path data in src/icon_data.inc is generated from it.

Lucide is distributed under the ISC License. A subset of its icons is
derived from Feather and carries the MIT License instead; both notices
are reproduced below in full, exactly as published with the set.

-------------------------------------------------------------------------------
Lucide - https://lucide.dev
-------------------------------------------------------------------------------

$lic
"@
$noticeFile = Join-Path $root 'THIRD-PARTY-NOTICES.txt'
[IO.File]::WriteAllText($noticeFile, $notice, (New-Object Text.UTF8Encoding $false))
Write-Host ("wrote {0}" -f $noticeFile)
